Feature 18
the-future-engineers-network/DevSandbox pull request #28
Opened 2023-10-04 21:35 UTC by abmercy035

Feat :
Started the noSetup Section.
Added the Section's title and its info test
Add the Illustrating Video. (vidoe url was treated as a static asset for now)

Issue Link : https://github.com/the-future-engineers-network/DevSandbox/issues/18

2023-10-05 13:55 UTC, thechinedu requested changes

2023-10-05 13:55 UTC, thechinedu commented on apps/docs/package.json
> +    "dev": "next dev -p 3000",
This should not be part of your PR. This file should not be changed

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +/* Recurring Sytles */
No need for these comments. They should be removed

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +/* My video Element is on the site but am having issue with the rendering  */
Remove this comment. It's not necessary

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +.noSetup .info {
Use a new line to separate css rules

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +.noSetup .info h2 {
Use a new line to separate css rules

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +.noSetup .info h2 span {
Use a new line to separate css rules.

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +.noSetup .info h2 span {
Add a class to the span element and use it directly here instead of using this overly specific combinator selector

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +}
Use a new line to separate css rules

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +.noSetup .info p span {
Use a new line to separate css rules.

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +.noSetup .noSetup_video {
Replace `.noSetup_video` with `noSetupVideo`

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +.noSetup .noSetup_video video {
Replace `.noSetup_video` with `noSetupVideo`. It seems `.noSetup_video` is the container for the video element. The class name should be changed to something that reflects that. Maybe `.videoContainer`

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.module.css
> +@media screen and (min-width: 551px) and (max-width: 1100px) {
There shouldn't be a need to be this restrictive. The min-width section should be enough. Additionally, there is no need to specify `screen`

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.tsx
> +*/}
Remove this comment

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/app/home/home.tsx
>            {/* TODO: Add no setup content here. The first bit of content has been set up for you. */}
You can remove this comment as well since the section is now being actively worked on

2023-10-05 13:55 UTC, thechinedu commented on apps/frontend/package.json
> +    "dev": "next dev -p 3001",
This should not be part of your PR. This file should not be changed

2023-10-10 07:08 UTC, abmercy035 commented on apps/docs/package.json
> +    "dev": "next dev -p 3000",
You mean i should add to git ignore?

2023-10-20 17:11 UTC, abmercy035 commented
Fixed Fonts and padding

2023-11-09 12:59 UTC, closed without merging